import type { Metadata } from "next";
import { Courier_Prime } from "next/font/google";
import "./globals.css";

const roboto = Courier_Prime({
  subsets: ["latin"],
  weight: ["400", "700"], // choose weights you need
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>{children}</body>
    </html>
  );
}
